<%@ Page Title="Finance Review" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Finance.aspx.cs" Inherits="BC.FixedAsset.Web.FixedAsset.Review.FinanceReview" %>
<asp:Content ID="Body" ContentPlaceHolderID="MainContent" runat="server">
<div class="page-head"><div><h1>Finance Review</h1><p>ตรวจสอบรายละเอียดและรูปภาพก่อนขึ้นทะเบียน หรือ Return พร้อมเหตุผล</p></div></div>
<asp:Label ID="lblMessage" runat="server" CssClass="message"/>
<section class="card table-card"><div class="table-wrap">
  <asp:GridView ID="gridReview" runat="server" AutoGenerateColumns="false" GridLines="None" CssClass="asset-table review-table" OnRowCommand="Grid_RowCommand" OnRowDataBound="Grid_RowDataBound">
    <Columns>
      <asp:TemplateField HeaderText="รูป"><ItemTemplate><img class="asset-thumb" src='<%# AttachmentUrl(Eval("ActualAttachmentId")) %>' alt="รูปทรัพย์สิน"/></ItemTemplate></asp:TemplateField>
      <asp:BoundField DataField="SurveyNo" HeaderText="เลขที่"/>
      <asp:TemplateField HeaderText="ทรัพย์สิน"><ItemTemplate><b><%# Eval("AssetName") %></b><small class="cell-sub"><%# Eval("SerialNumber") %></small></ItemTemplate></asp:TemplateField>
      <asp:BoundField DataField="PurchaseOrderNo" HeaderText="PO"/>
      <asp:BoundField DataField="EstimatedValue" HeaderText="Estimated Value" DataFormatString="{0:N2}"/>
      <asp:BoundField DataField="Custodian" HeaderText="ผู้ดูแล"/>
      <asp:TemplateField HeaderText="ดำเนินการ"><ItemTemplate><div class="row-actions"><asp:LinkButton ID="btnDetail" runat="server" CssClass="button small outline" CommandName="Detail" CommandArgument='<%# Eval("SurveyId") %>'>ดูรายละเอียด</asp:LinkButton><button type="button" class="button small primary" onclick='openApproveDialog(<%# Eval("SurveyId") %>)'>Register</button><button type="button" class="button small danger" onclick='openReturnDialog(<%# Eval("SurveyId") %>)'>Return</button></div></ItemTemplate></asp:TemplateField>
    </Columns>
  </asp:GridView>
</div></section>

<asp:Panel ID="pnlDetail" runat="server" CssClass="modal-layer" Visible="false"><div class="modal-card review-detail-modal"><div class="modal-head"><div><span class="detail-eyebrow review-eyebrow">FINANCE VERIFICATION</span><h2>รายละเอียดก่อนขึ้นทะเบียน</h2><p class="muted">ตรวจสอบข้อมูล รูปภาพ และมูลค่าทรัพย์สิน</p></div><asp:Button ID="btnCloseDetail" runat="server" Text="×" CssClass="icon-button" OnClick="CloseDetail_Click" CausesValidation="false"/></div><div class="detail-images review-gallery"><asp:Repeater ID="repImages" runat="server"><ItemTemplate><figure><img src='<%# AttachmentUrl(Eval("AttachmentId")) %>' alt='<%# PhotoLabel(Eval("AttachmentType")) %>'/><figcaption><%# PhotoLabel(Eval("AttachmentType")) %></figcaption></figure></ItemTemplate></asp:Repeater></div><asp:Literal ID="litDetail" runat="server"/><div class="modal-actions review-detail-actions"><asp:Button ID="btnApproveFromDetail" runat="server" CssClass="button primary" Text="Register รายการนี้" OnClick="ApproveFromDetail_Click" OnClientClick="return confirm('ยืนยันการขึ้นทะเบียนรายการนี้?');"/></div></div></asp:Panel>

<div id="approveDialog" class="modal-layer" role="dialog" aria-modal="true" aria-labelledby="approveTitle" hidden><div class="modal-card return-dialog"><div class="modal-head"><div><h2 id="approveTitle">ยืนยันการ Register</h2><p class="muted">ขึ้นทะเบียนและสร้างเลข Fixed Asset สำหรับรายการนี้?</p></div><button type="button" class="icon-button" onclick="closeApproveDialog()" aria-label="ปิด">×</button></div><asp:HiddenField ID="hidApproveId" runat="server"/><div class="modal-actions"><button type="button" class="button outline" onclick="closeApproveDialog()">ยกเลิก</button><asp:Button ID="btnApprove" runat="server" CssClass="button primary" Text="ยืนยัน Register" OnClick="Approve_Click"/></div></div></div>
<div id="returnDialog" class="modal-layer" role="dialog" aria-modal="true" aria-labelledby="returnTitle" hidden><div class="modal-card return-dialog"><div class="modal-head"><h2 id="returnTitle">เหตุผลสำหรับ Return</h2><button type="button" class="icon-button" onclick="closeReturnDialog()" aria-label="ปิด">×</button></div><div class="field"><label for="<%= txtReason.ClientID %>">เหตุผลสำหรับ Return *</label><asp:TextBox ID="txtReason" runat="server" TextMode="MultiLine" Rows="4"/></div><asp:HiddenField ID="hidReturnId" runat="server"/><div class="modal-actions"><button type="button" class="button outline" onclick="closeReturnDialog()">ยกเลิก</button><asp:Button ID="btnReturn" runat="server" CssClass="button danger" Text="ยืนยัน Return" OnClick="Return_Click" OnClientClick="return validateReturnDialog();"/></div></div></div>
<script>function openApproveDialog(id){document.getElementById('<%= hidApproveId.ClientID %>').value=id;document.getElementById('approveDialog').hidden=false;document.getElementById('<%= btnApprove.ClientID %>').focus()}function closeApproveDialog(){document.getElementById('approveDialog').hidden=true}function openReturnDialog(id){document.getElementById('<%= hidReturnId.ClientID %>').value=id;var dialog=document.getElementById('returnDialog');dialog.hidden=false;document.getElementById('<%= txtReason.ClientID %>').focus()}function closeReturnDialog(){document.getElementById('returnDialog').hidden=true}function validateReturnDialog(){var reason=document.getElementById('<%= txtReason.ClientID %>');if(!reason.value.trim()){reason.focus();return false}return true}</script>
</asp:Content>
