USE [master];
GO
IF DB_ID(N'BCFixedAsset') IS NULL
BEGIN
    CREATE DATABASE [BCFixedAsset];
END
GO
ALTER DATABASE [BCFixedAsset] SET RECOVERY SIMPLE;
ALTER DATABASE [BCFixedAsset] SET READ_COMMITTED_SNAPSHOT ON;
GO
