USE [BCFixedAsset];
GO
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name='sec') EXEC('CREATE SCHEMA sec');
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name='mst') EXEC('CREATE SCHEMA mst');
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name='fa') EXEC('CREATE SCHEMA fa');
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name='audit') EXEC('CREATE SCHEMA audit');
GO
CREATE TABLE mst.Companies(CompanyId int IDENTITY PRIMARY KEY,CompanyCode nvarchar(20) NOT NULL UNIQUE,CompanyName nvarchar(200) NOT NULL,IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE mst.Divisions(DivisionId int IDENTITY PRIMARY KEY,CompanyId int NOT NULL REFERENCES mst.Companies(CompanyId),DivisionCode nvarchar(30) NOT NULL,DivisionName nvarchar(150) NOT NULL,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT UQ_Division UNIQUE(CompanyId,DivisionCode));
CREATE TABLE mst.Departments(DepartmentId int IDENTITY PRIMARY KEY,DivisionId int NULL REFERENCES mst.Divisions(DivisionId),DepartmentCode nvarchar(30) NOT NULL UNIQUE,DepartmentName nvarchar(150) NOT NULL,IsActive bit NOT NULL DEFAULT 1,ActiveManagerUserId int NULL);
CREATE TABLE mst.AssetCategories(CategoryId int IDENTITY PRIMARY KEY,CategoryCode nvarchar(20) NOT NULL UNIQUE,CategoryName nvarchar(150) NOT NULL,UsefulLifeMonths int NULL,IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE mst.Uoms(UomId int IDENTITY PRIMARY KEY,UomCode nvarchar(20) NOT NULL UNIQUE,UomNameTh nvarchar(100) NOT NULL,UomNameEn nvarchar(100) NOT NULL,IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE mst.AssetConditions(ConditionId int IDENTITY PRIMARY KEY,ConditionCode nvarchar(30) NOT NULL UNIQUE,ConditionName nvarchar(100) NOT NULL,DisplayOrder int NOT NULL DEFAULT 0,IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE mst.Buildings(BuildingId int IDENTITY PRIMARY KEY,BuildingCode nvarchar(30) NOT NULL UNIQUE,BuildingName nvarchar(150) NOT NULL,IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE mst.Floors(FloorId int IDENTITY PRIMARY KEY,BuildingId int NOT NULL REFERENCES mst.Buildings(BuildingId),FloorCode nvarchar(30) NOT NULL,FloorName nvarchar(100) NOT NULL,DisplayOrder int NOT NULL DEFAULT 0,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT UQ_Floor UNIQUE(BuildingId,FloorCode));
CREATE TABLE mst.Rooms(RoomId int IDENTITY PRIMARY KEY,FloorId int NOT NULL REFERENCES mst.Floors(FloorId),RoomCode nvarchar(30) NOT NULL,RoomName nvarchar(150) NOT NULL,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT UQ_Room UNIQUE(FloorId,RoomCode));
GO
CREATE TABLE sec.Users(UserId int IDENTITY PRIMARY KEY,UserName nvarchar(100) NOT NULL UNIQUE,Email nvarchar(256) NOT NULL,Phone nvarchar(50) NULL,FirstName nvarchar(100) NOT NULL,LastName nvarchar(100) NOT NULL,DisplayName AS LTRIM(RTRIM(FirstName+N' '+LastName)) PERSISTED,Position nvarchar(150) NULL,DivisionId int NULL REFERENCES mst.Divisions(DivisionId),DepartmentId int NULL REFERENCES mst.Departments(DepartmentId),ProfileImagePath nvarchar(500) NULL,AccountType tinyint NOT NULL DEFAULT 0,ExternalObjectId uniqueidentifier NULL,MustChangePassword bit NOT NULL DEFAULT 0,IsActive bit NOT NULL DEFAULT 1,CreatedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),ModifiedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),RowVersion rowversion);
ALTER TABLE mst.Departments ADD CONSTRAINT FK_Department_Manager FOREIGN KEY(ActiveManagerUserId) REFERENCES sec.Users(UserId);
CREATE TABLE sec.UserCredentials(UserId int PRIMARY KEY REFERENCES sec.Users(UserId),PasswordHash varbinary(64) NULL,PasswordSalt varbinary(64) NULL,PasswordIterations int NULL,PasswordAlgorithm nvarchar(50) NULL,PasswordChangedUtc datetime2 NULL,PasswordExpiresUtc datetime2 NULL,FailedLoginCount int NOT NULL DEFAULT 0,LockedUntilUtc datetime2 NULL,LastLoginUtc datetime2 NULL);
CREATE TABLE sec.PasswordHistory(PasswordHistoryId bigint IDENTITY PRIMARY KEY,UserId int NOT NULL REFERENCES sec.Users(UserId),PasswordHash varbinary(64) NOT NULL,PasswordSalt varbinary(64) NOT NULL,PasswordIterations int NOT NULL,CreatedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE sec.PasswordPolicies(PolicyId int IDENTITY PRIMARY KEY,PolicyName nvarchar(100) NOT NULL,MinimumLength int NOT NULL,RequireUppercase bit NOT NULL,RequireLowercase bit NOT NULL,RequireNumber bit NOT NULL,RequireSpecialCharacter bit NOT NULL,PasswordHistoryCount int NOT NULL,MaximumFailedAttempts int NOT NULL,LockoutMinutes int NOT NULL,ExpiryDays int NOT NULL,IsActive bit NOT NULL DEFAULT 1,ModifiedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE sec.Applications(ApplicationId int IDENTITY PRIMARY KEY,ApplicationCode nvarchar(50) NOT NULL UNIQUE,NameTh nvarchar(150) NOT NULL,NameEn nvarchar(150) NOT NULL,DescriptionTh nvarchar(500) NULL,DescriptionEn nvarchar(500) NULL,IconText nvarchar(20) NULL,IconPath nvarchar(500) NULL,TargetUrl nvarchar(500) NOT NULL,DisplayOrder int NOT NULL DEFAULT 0,IsActive bit NOT NULL DEFAULT 1,CreatedByUserId int NULL REFERENCES sec.Users(UserId),ModifiedByUserId int NULL REFERENCES sec.Users(UserId),CreatedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),ModifiedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),RowVersion rowversion);
CREATE TABLE sec.Roles(RoleId int IDENTITY PRIMARY KEY,RoleCode nvarchar(50) NOT NULL UNIQUE,RoleName nvarchar(150) NOT NULL,IsSystemRole bit NOT NULL DEFAULT 0,IsActive bit NOT NULL DEFAULT 1);
CREATE TABLE sec.UserApplicationRoles(UserId int NOT NULL REFERENCES sec.Users(UserId),ApplicationId int NOT NULL REFERENCES sec.Applications(ApplicationId),RoleId int NOT NULL REFERENCES sec.Roles(RoleId),IsActive bit NOT NULL DEFAULT 1,CreatedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(UserId,ApplicationId,RoleId));
CREATE TABLE sec.RolePermissions(RoleId int NOT NULL REFERENCES sec.Roles(RoleId),ModuleCode nvarchar(80) NOT NULL,ActionCode nvarchar(80) NOT NULL,IsAllowed bit NOT NULL DEFAULT 1,PRIMARY KEY(RoleId,ModuleCode,ActionCode));
GO
CREATE SEQUENCE fa.SurveyNoSequence AS bigint START WITH 1 INCREMENT BY 1;
CREATE TABLE fa.AssetSurveys(SurveyId bigint IDENTITY PRIMARY KEY,SurveyNo nvarchar(50) NOT NULL UNIQUE,SurveyDate date NOT NULL,SurveyorUserId int NOT NULL REFERENCES sec.Users(UserId),DepartmentId int NOT NULL REFERENCES mst.Departments(DepartmentId),CustodianUserId int NULL REFERENCES sec.Users(UserId),AssetName nvarchar(250) NOT NULL,CategoryId int NOT NULL REFERENCES mst.AssetCategories(CategoryId),Brand nvarchar(120) NULL,ModelDescription nvarchar(300) NULL,SerialNumber nvarchar(150) NULL,OwnershipType nvarchar(50) NULL,ConditionId int NOT NULL REFERENCES mst.AssetConditions(ConditionId),WidthCm decimal(18,2) NULL,LengthCm decimal(18,2) NULL,HeightCm decimal(18,2) NULL,WeightKg decimal(18,2) NULL,Quantity decimal(18,2) NOT NULL DEFAULT 1,UomId int NOT NULL REFERENCES mst.Uoms(UomId),BuildingId int NOT NULL REFERENCES mst.Buildings(BuildingId),FloorId int NOT NULL REFERENCES mst.Floors(FloorId),RoomId int NOT NULL REFERENCES mst.Rooms(RoomId),ReceivedDate date NULL,PurchaseOrderNo nvarchar(100) NULL,EstimatedValue decimal(18,2) NULL,PurchaseEvidenceRef nvarchar(500) NULL,PurchaseDate date NULL,MissingDimensionReason nvarchar(500) NULL,Remark nvarchar(1000) NULL,Status nvarchar(30) NOT NULL DEFAULT 'Draft',CreatedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),ModifiedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),RowVersion rowversion);
CREATE INDEX IX_AssetSurveys_Status_Department ON fa.AssetSurveys(Status,DepartmentId) INCLUDE(SurveyNo,AssetName,ModifiedUtc);
CREATE TABLE fa.AssetSurveyAttachments(AttachmentId bigint IDENTITY PRIMARY KEY,SurveyId bigint NOT NULL REFERENCES fa.AssetSurveys(SurveyId),AttachmentType nvarchar(50) NOT NULL,OriginalFileName nvarchar(260) NOT NULL,StoredFileName nvarchar(260) NOT NULL,RelativePath nvarchar(500) NOT NULL,ContentType nvarchar(100) NOT NULL,FileSizeBytes bigint NOT NULL,UploadedByUserId int NOT NULL REFERENCES sec.Users(UserId),UploadedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE fa.ApprovalTasks(ApprovalTaskId bigint IDENTITY PRIMARY KEY,SurveyId bigint NOT NULL REFERENCES fa.AssetSurveys(SurveyId),Stage nvarchar(30) NOT NULL,AssignedUserId int NULL REFERENCES sec.Users(UserId),AssignedDepartmentId int NULL REFERENCES mst.Departments(DepartmentId),Status nvarchar(30) NOT NULL,Decision nvarchar(30) NULL,Comment nvarchar(1000) NULL,AssignedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),CompletedUtc datetime2 NULL,CompletedByUserId int NULL REFERENCES sec.Users(UserId),RowVersion rowversion);
CREATE TABLE fa.FixedAssets(FixedAssetId bigint IDENTITY PRIMARY KEY,FixedAssetNo nvarchar(80) NOT NULL UNIQUE,SourceSurveyId bigint NULL REFERENCES fa.AssetSurveys(SurveyId),AssetName nvarchar(250) NOT NULL,CategoryId int NOT NULL REFERENCES mst.AssetCategories(CategoryId),Brand nvarchar(120) NULL,ModelDescription nvarchar(300) NULL,SerialNumber nvarchar(150) NULL,DepartmentId int NOT NULL REFERENCES mst.Departments(DepartmentId),CustodianUserId int NULL REFERENCES sec.Users(UserId),BuildingId int NULL REFERENCES mst.Buildings(BuildingId),FloorId int NULL REFERENCES mst.Floors(FloorId),RoomId int NULL REFERENCES mst.Rooms(RoomId),Quantity decimal(18,2) NOT NULL DEFAULT 1,UomId int NOT NULL REFERENCES mst.Uoms(UomId),ReceivedDate date NULL,PurchaseOrderNo nvarchar(100) NULL,AcquisitionCost decimal(18,2) NULL,AssetStatus nvarchar(30) NOT NULL DEFAULT 'Active',IsActive bit NOT NULL DEFAULT 1,CreatedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),ModifiedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),RowVersion rowversion);
CREATE TABLE fa.AssetNumberSchemes(SchemeId int IDENTITY PRIMARY KEY,CompanyId int NOT NULL REFERENCES mst.Companies(CompanyId),SchemeName nvarchar(150) NOT NULL,Pattern nvarchar(200) NOT NULL,SequenceDigits int NOT NULL,SequenceScope nvarchar(50) NOT NULL,ResetPolicy nvarchar(20) NOT NULL,StartValue int NOT NULL DEFAULT 1,EffectiveDate date NOT NULL,IsActive bit NOT NULL DEFAULT 1,ModifiedByUserId int NULL REFERENCES sec.Users(UserId),ModifiedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE fa.AssetNumberCounters(CounterId bigint IDENTITY PRIMARY KEY,SchemeId int NOT NULL REFERENCES fa.AssetNumberSchemes(SchemeId),ScopeKey nvarchar(200) NOT NULL,CurrentValue bigint NOT NULL,ModifiedUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_AssetNumberCounter UNIQUE(SchemeId,ScopeKey));
CREATE TABLE audit.AuditLogs(AuditLogId bigint IDENTITY PRIMARY KEY,OccurredUtc datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),UserId int NULL REFERENCES sec.Users(UserId),ApplicationCode nvarchar(50) NULL,ModuleCode nvarchar(80) NULL,ActionCode nvarchar(80) NOT NULL,EntityName nvarchar(128) NULL,EntityId nvarchar(100) NULL,OldValues nvarchar(max) NULL,NewValues nvarchar(max) NULL,IpAddress nvarchar(64) NULL,CorrelationId uniqueidentifier NOT NULL DEFAULT NEWID());
GO
CREATE OR ALTER PROCEDURE fa.usp_SaveAssetSurvey
 @SurveyId bigint,@SurveyorUserId int,@SurveyDate date,@DepartmentId int,@CustodianUserId int=NULL,@AssetName nvarchar(250),@CategoryId int,@Brand nvarchar(120)=NULL,@ModelDescription nvarchar(300)=NULL,@SerialNumber nvarchar(150)=NULL,@OwnershipType nvarchar(50)=NULL,@ConditionId int,@WidthCm decimal(18,2)=NULL,@LengthCm decimal(18,2)=NULL,@HeightCm decimal(18,2)=NULL,@WeightKg decimal(18,2)=NULL,@Quantity decimal(18,2),@UomId int,@BuildingId int,@FloorId int,@RoomId int,@ReceivedDate date=NULL,@PurchaseOrderNo nvarchar(100)=NULL,@EstimatedValue decimal(18,2)=NULL,@MissingDimensionReason nvarchar(500)=NULL,@Remark nvarchar(1000)=NULL,@SavedSurveyId bigint OUTPUT
AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;
 IF @SurveyId=0 BEGIN DECLARE @n bigint=NEXT VALUE FOR fa.SurveyNoSequence;DECLARE @no nvarchar(50)=N'SUR-'+CONVERT(nvarchar(4),YEAR(@SurveyDate))+N'-'+RIGHT(REPLICATE('0',6)+CONVERT(nvarchar(20),@n),6);
  INSERT fa.AssetSurveys(SurveyNo,SurveyDate,SurveyorUserId,DepartmentId,CustodianUserId,AssetName,CategoryId,Brand,ModelDescription,SerialNumber,OwnershipType,ConditionId,WidthCm,LengthCm,HeightCm,WeightKg,Quantity,UomId,BuildingId,FloorId,RoomId,ReceivedDate,PurchaseOrderNo,EstimatedValue,MissingDimensionReason,Remark)
  VALUES(@no,@SurveyDate,@SurveyorUserId,@DepartmentId,@CustodianUserId,@AssetName,@CategoryId,@Brand,@ModelDescription,@SerialNumber,@OwnershipType,@ConditionId,@WidthCm,@LengthCm,@HeightCm,@WeightKg,@Quantity,@UomId,@BuildingId,@FloorId,@RoomId,@ReceivedDate,@PurchaseOrderNo,@EstimatedValue,@MissingDimensionReason,@Remark);SET @SavedSurveyId=SCOPE_IDENTITY();END
 ELSE BEGIN UPDATE fa.AssetSurveys SET SurveyDate=@SurveyDate,DepartmentId=@DepartmentId,CustodianUserId=@CustodianUserId,AssetName=@AssetName,CategoryId=@CategoryId,Brand=@Brand,ModelDescription=@ModelDescription,SerialNumber=@SerialNumber,OwnershipType=@OwnershipType,ConditionId=@ConditionId,WidthCm=@WidthCm,LengthCm=@LengthCm,HeightCm=@HeightCm,WeightKg=@WeightKg,Quantity=@Quantity,UomId=@UomId,BuildingId=@BuildingId,FloorId=@FloorId,RoomId=@RoomId,ReceivedDate=@ReceivedDate,PurchaseOrderNo=@PurchaseOrderNo,EstimatedValue=@EstimatedValue,MissingDimensionReason=@MissingDimensionReason,Remark=@Remark,ModifiedUtc=SYSUTCDATETIME() WHERE SurveyId=@SurveyId AND Status IN('Draft','Returned');SET @SavedSurveyId=@SurveyId;END
END
GO
CREATE OR ALTER PROCEDURE fa.usp_GenerateFixedAssetNumber @CompanyId int,@CategoryId int,@EffectiveDate date,@RequestedByUserId int,@AssetNumber nvarchar(80) OUTPUT
AS
BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRAN;
 DECLARE @SchemeId int,@Pattern nvarchar(200),@Digits int,@SequenceScope nvarchar(50),@ResetPolicy nvarchar(20),@CompanyCode nvarchar(20),@CategoryCode nvarchar(20),@ScopeKey nvarchar(200),@Next bigint;
 SELECT TOP(1) @SchemeId=SchemeId,@Pattern=Pattern,@Digits=SequenceDigits,@SequenceScope=SequenceScope,@ResetPolicy=ResetPolicy FROM fa.AssetNumberSchemes WITH(UPDLOCK,HOLDLOCK) WHERE CompanyId=@CompanyId AND IsActive=1 AND EffectiveDate<=@EffectiveDate ORDER BY EffectiveDate DESC;
 IF @SchemeId IS NULL THROW 50002,'No active Fixed Asset numbering scheme was found.',1;
 SELECT @CompanyCode=CompanyCode FROM mst.Companies WHERE CompanyId=@CompanyId;SELECT @CategoryCode=CategoryCode FROM mst.AssetCategories WHERE CategoryId=@CategoryId;
 SET @ScopeKey=CASE WHEN @SequenceScope=N'Global' THEN N'GLOBAL' WHEN @SequenceScope=N'Company + Year' THEN @CompanyCode ELSE @CompanyCode+N'|'+@CategoryCode END;
 IF @ResetPolicy=N'Yearly' SET @ScopeKey=@ScopeKey+N'|'+CONVERT(nvarchar(4),YEAR(@EffectiveDate));
 IF @ResetPolicy=N'Monthly' SET @ScopeKey=@ScopeKey+N'|'+CONVERT(nvarchar(6),@EffectiveDate,112);
 UPDATE fa.AssetNumberCounters WITH(UPDLOCK,HOLDLOCK) SET CurrentValue=CurrentValue+1,ModifiedUtc=SYSUTCDATETIME(),@Next=CurrentValue+1 WHERE SchemeId=@SchemeId AND ScopeKey=@ScopeKey;
 IF @@ROWCOUNT=0 BEGIN SELECT @Next=StartValue FROM fa.AssetNumberSchemes WHERE SchemeId=@SchemeId;INSERT fa.AssetNumberCounters(SchemeId,ScopeKey,CurrentValue) VALUES(@SchemeId,@ScopeKey,@Next);END
 SET @AssetNumber=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@Pattern,N'{COMPANY}',@CompanyCode),N'{CATEGORY}',@CategoryCode),N'{YEAR}',CONVERT(nvarchar(4),YEAR(@EffectiveDate))),N'{MONTH}',RIGHT(N'0'+CONVERT(nvarchar(2),MONTH(@EffectiveDate)),2)),N'{SEQ}',RIGHT(REPLICATE('0',@Digits)+CONVERT(nvarchar(20),@Next),@Digits));COMMIT;
END
GO
