using BC.FixedAsset.Core.Models;using BC.FixedAsset.Services;using System;using System.Data;
namespace BC.FixedAsset.Web.Admin
{
 public partial class Applications:SecurePage
 {
  protected global::System.Web.UI.WebControls.GridView gridApplications;protected global::System.Web.UI.WebControls.Panel pnlEditor;protected global::System.Web.UI.WebControls.Label lblMessage;protected global::System.Web.UI.WebControls.HiddenField hidApplicationId;protected global::System.Web.UI.WebControls.TextBox txtCode,txtIcon,txtIconPath,txtNameTh,txtNameEn,txtDescriptionTh,txtTargetUrl,txtDisplayOrder;protected global::System.Web.UI.WebControls.CheckBox chkActive;protected global::System.Web.UI.WebControls.Button btnNew,btnSave;
  private readonly AdministrationService service=new AdministrationService();protected void Page_Load(object s,EventArgs e){if(!IsPostBack)BindGrid();}private void BindGrid(){gridApplications.DataSource=service.GetApplications();gridApplications.DataBind();}
  protected void New_Click(object s,EventArgs e){hidApplicationId.Value="0";txtCode.Text=txtIcon.Text=txtIconPath.Text=txtNameTh.Text=txtNameEn.Text=txtDescriptionTh.Text="";txtTargetUrl.Text="/";txtDisplayOrder.Text="10";chkActive.Checked=true;pnlEditor.Visible=true;}
  protected void Grid_RowCommand(object s,global::System.Web.UI.WebControls.GridViewCommandEventArgs e){if(e.CommandName!="EditApplication")return;var table=service.GetApplications();var rows=table.Select("ApplicationId="+Convert.ToInt32(e.CommandArgument));if(rows.Length==0)return;var row=rows[0];hidApplicationId.Value=Convert.ToString(row["ApplicationId"]);txtCode.Text=Convert.ToString(row["ApplicationCode"]);txtIcon.Text=Convert.ToString(row["IconText"]);txtIconPath.Text=Convert.ToString(row["IconPath"]);txtNameTh.Text=Convert.ToString(row["NameTh"]);txtNameEn.Text=Convert.ToString(row["NameEn"]);txtDescriptionTh.Text=Convert.ToString(row["DescriptionTh"]);txtTargetUrl.Text=Convert.ToString(row["TargetUrl"]);txtDisplayOrder.Text=Convert.ToString(row["DisplayOrder"]);chkActive.Checked=Convert.ToBoolean(row["IsActive"]);pnlEditor.Visible=true;}
  protected void Save_Click(object s,EventArgs e){try{service.SaveApplication(new ApplicationDefinition{ApplicationId=Convert.ToInt32(hidApplicationId.Value),ApplicationCode=txtCode.Text.Trim(),IconText=txtIcon.Text.Trim(),IconPath=txtIconPath.Text.Trim(),NameTh=txtNameTh.Text.Trim(),NameEn=txtNameEn.Text.Trim(),DescriptionTh=txtDescriptionTh.Text.Trim(),DescriptionEn=txtDescriptionTh.Text.Trim(),TargetUrl=txtTargetUrl.Text.Trim(),DisplayOrder=Convert.ToInt32(txtDisplayOrder.Text),IsActive=chkActive.Checked},CurrentUser.Id);lblMessage.CssClass="message";lblMessage.Text="บันทึก Application เรียบร้อย";pnlEditor.Visible=false;BindGrid();}catch(Exception ex){lblMessage.CssClass="message";lblMessage.Text=Server.HtmlEncode(ex.Message);}}
 }
}
