<%@ Page Title="Master Data" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="MasterData.aspx.cs" Inherits="BC.FixedAsset.Web.Admin.MasterData" %>
<asp:Content ID="Body" ContentPlaceHolderID="MainContent" runat="server">
<div class="admin-tabs"><a href="Applications.aspx">▣ Application Portal</a><a href="Users.aspx">♙ ผู้ใช้และสิทธิ์</a><a class="active" href="MasterData.aspx">▤ ข้อมูลกลาง</a><a href="../FixedAsset/Numbering.aspx">⚙ เลขทรัพย์สิน</a></div>
<div class="page-head"><div><h1>Master Data</h1><p>จัดการข้อมูลอ้างอิงสำหรับ Survey และทะเบียนทรัพย์สิน</p></div><asp:Button ID="btnNew" runat="server" CssClass="button primary" Text="＋ เพิ่มข้อมูล" OnClick="New_Click"/></div>
<asp:Label ID="lblMessage" runat="server" CssClass="message"/>
<section class="card table-card"><div class="table-toolbar"><div class="field master-type-select"><label for="<%= ddlKind.ClientID %>">ประเภทข้อมูล</label><asp:DropDownList ID="ddlKind" runat="server" AutoPostBack="true" OnSelectedIndexChanged="Kind_Changed"/></div><span class="badge"><asp:Literal ID="litCount" runat="server"/></span></div>
<div class="table-wrap"><asp:GridView ID="gridItems" runat="server" AutoGenerateColumns="false" GridLines="None" OnRowCommand="Grid_RowCommand" CssClass="asset-table"><Columns>
<asp:BoundField DataField="Code" HeaderText="Code"/><asp:BoundField DataField="Name" HeaderText="Name"/><asp:BoundField DataField="SecondaryName" HeaderText="English Name"/><asp:BoundField DataField="ParentName" HeaderText="Parent"/><asp:BoundField DataField="NumericValue" HeaderText="Number"/>
<asp:TemplateField HeaderText="Status"><ItemTemplate><%# Convert.ToBoolean(Eval("IsActive")) ? "Active" : "Inactive" %></ItemTemplate></asp:TemplateField>
<asp:TemplateField HeaderText="Actions"><ItemTemplate><div class="row-actions"><asp:LinkButton runat="server" CssClass="button small outline" CommandName="EditItem" CommandArgument='<%# Eval("Id") %>'>แก้ไข</asp:LinkButton><button type="button" class="button small danger" onclick='openDeleteDialog(<%# Eval("Id") %>)'>ลบ</button></div></ItemTemplate></asp:TemplateField>
</Columns></asp:GridView></div></section>
<asp:Panel ID="pnlEditor" runat="server" CssClass="modal-layer" Visible="false"><div class="modal-card return-dialog"><div class="modal-head"><div><h2><asp:Literal ID="litEditorTitle" runat="server"/></h2><p class="muted"><asp:Literal ID="litEditorKind" runat="server"/></p></div><asp:Button ID="btnCancel" runat="server" CssClass="icon-button" Text="×" OnClick="Cancel_Click" CausesValidation="false"/></div>
<asp:Label ID="lblEditorError" runat="server" CssClass="message"/><asp:HiddenField ID="hidId" runat="server"/><div class="master-editor-fields"><div class="field"><label for="<%= txtCode.ClientID %>">Code *</label><asp:TextBox ID="txtCode" runat="server"/></div><div class="field"><label for="<%= txtName.ClientID %>">Name *</label><asp:TextBox ID="txtName" runat="server"/></div>
<asp:Panel ID="pnlSecondary" runat="server" CssClass="field"><label for="<%= txtSecondary.ClientID %>">English name *</label><asp:TextBox ID="txtSecondary" runat="server"/></asp:Panel>
<asp:Panel ID="pnlParent" runat="server" CssClass="field"><label for="<%= ddlParent.ClientID %>">Parent</label><asp:DropDownList ID="ddlParent" runat="server"/></asp:Panel>
<asp:Panel ID="pnlNumeric" runat="server" CssClass="field"><label for="<%= txtNumeric.ClientID %>"><asp:Literal ID="litNumericLabel" runat="server"/></label><asp:TextBox ID="txtNumeric" runat="server" TextMode="Number" min="0"/></asp:Panel>
<asp:Panel ID="pnlActive" runat="server" CssClass="field"><label><asp:CheckBox ID="chkActive" runat="server"/> Active</label></asp:Panel></div>
<div class="modal-actions"><asp:Button runat="server" CssClass="button outline" Text="ยกเลิก" OnClick="Cancel_Click" CausesValidation="false"/><asp:Button ID="btnSave" runat="server" CssClass="button primary" Text="บันทึก" OnClick="Save_Click"/></div></div></asp:Panel>
<div id="deleteDialog" class="modal-layer" role="dialog" aria-modal="true" aria-labelledby="deleteTitle" hidden><div class="modal-card return-dialog"><div class="modal-head"><div><h2 id="deleteTitle">ยืนยันการลบ</h2><p class="muted">ลบข้อมูลนี้ออกจาก Master Data?</p></div><button type="button" class="icon-button" onclick="closeDeleteDialog()" aria-label="ปิด">×</button></div><p class="muted">รายการที่ถูกใช้งานอยู่จะลบไม่ได้ ให้แก้ไขเป็น Inactive แทน</p><asp:HiddenField ID="hidDeleteId" runat="server"/><div class="modal-actions"><button type="button" class="button outline" onclick="closeDeleteDialog()">ยกเลิก</button><asp:Button ID="btnDelete" runat="server" CssClass="button danger" Text="ลบข้อมูล" OnClick="Delete_Click"/></div></div></div>
<script>function openDeleteDialog(id){document.getElementById('<%= hidDeleteId.ClientID %>').value=id;document.getElementById('deleteDialog').hidden=false;document.getElementById('<%= btnDelete.ClientID %>').focus()}function closeDeleteDialog(){document.getElementById('deleteDialog').hidden=true}</script>
</asp:Content>
