using BC.FixedAsset.Core.Models;using System;using System.Data;using System.Data.SqlClient;
namespace BC.FixedAsset.Data
{
 public sealed class FixedAssetRepository
 {
  public AssetNumberScheme GetNumberScheme(){const string sql=@"SELECT TOP(1) SchemeId,CompanyId,SchemeName,Pattern,SequenceDigits,SequenceScope,ResetPolicy,StartValue,EffectiveDate,IsActive FROM fa.AssetNumberSchemes WHERE IsActive=1 ORDER BY EffectiveDate DESC,SchemeId DESC;";using(var c=Db.OpenConnection())using(var cmd=new SqlCommand(sql,c))using(var r=cmd.ExecuteReader()){if(!r.Read())return null;return new AssetNumberScheme{SchemeId=Convert.ToInt32(r[0]),CompanyId=Convert.ToInt32(r[1]),SchemeName=Convert.ToString(r[2]),Pattern=Convert.ToString(r[3]),SequenceDigits=Convert.ToInt32(r[4]),SequenceScope=Convert.ToString(r[5]),ResetPolicy=Convert.ToString(r[6]),StartValue=Convert.ToInt32(r[7]),EffectiveDate=Convert.ToDateTime(r[8]),IsActive=Convert.ToBoolean(r[9])};}}
  public void SaveNumberScheme(AssetNumberScheme scheme,int userId){const string sql=@"UPDATE fa.AssetNumberSchemes SET Pattern=@Pattern,SequenceDigits=@Digits,SequenceScope=@Scope,ResetPolicy=@Reset,StartValue=@StartValue,ModifiedByUserId=@UserId,ModifiedUtc=SYSUTCDATETIME() WHERE SchemeId=@SchemeId AND IsActive=1;";using(var c=Db.OpenConnection())using(var cmd=new SqlCommand(sql,c)){Add(cmd,"@Pattern",scheme.Pattern,SqlDbType.NVarChar,200);Add(cmd,"@Digits",scheme.SequenceDigits,SqlDbType.Int);Add(cmd,"@Scope",scheme.SequenceScope,SqlDbType.NVarChar,50);Add(cmd,"@Reset",scheme.ResetPolicy,SqlDbType.NVarChar,20);Add(cmd,"@StartValue",scheme.StartValue,SqlDbType.Int);Add(cmd,"@UserId",userId,SqlDbType.Int);Add(cmd,"@SchemeId",scheme.SchemeId,SqlDbType.Int);if(cmd.ExecuteNonQuery()!=1)throw new InvalidOperationException("Active numbering scheme was not found.");}}
  public DashboardSummary GetDashboard(){const string sql=@"SELECT (SELECT COUNT(*) FROM fa.FixedAssets WHERE IsActive=1) TotalAssets,(SELECT COUNT(*) FROM fa.AssetSurveys WHERE Status='Draft') DraftSurveys,(SELECT COUNT(*) FROM fa.AssetSurveys WHERE Status='ManagerReview') PendingManager,(SELECT COUNT(*) FROM fa.AssetSurveys WHERE Status='FinanceReview') PendingFinance,(SELECT ISNULL(SUM(EstimatedValue),0) FROM fa.AssetSurveys) TotalEstimatedValue;";using(var c=Db.OpenConnection())using(var cmd=new SqlCommand(sql,c))using(var r=cmd.ExecuteReader()){r.Read();return new DashboardSummary{TotalAssets=Convert.ToInt32(r[0]),DraftSurveys=Convert.ToInt32(r[1]),PendingManager=Convert.ToInt32(r[2]),PendingFinance=Convert.ToInt32(r[3]),TotalEstimatedValue=Convert.ToDecimal(r[4])};}}
  public DataTable GetReference(string type){string sql;switch(type){case "Department":sql="SELECT DepartmentId Id,DepartmentName Name FROM mst.Departments WHERE IsActive=1 ORDER BY DepartmentName";break;case "Category":sql="SELECT CategoryId Id,CategoryName Name FROM mst.AssetCategories WHERE IsActive=1 ORDER BY CategoryName";break;case "Condition":sql="SELECT ConditionId Id,ConditionName Name FROM mst.AssetConditions WHERE IsActive=1 ORDER BY DisplayOrder";break;case "Uom":sql="SELECT UomId Id,UomCode Name FROM mst.Uoms WHERE IsActive=1 ORDER BY UomCode";break;case "User":sql="SELECT UserId Id,DisplayName Name FROM sec.Users WHERE IsActive=1 ORDER BY DisplayName";break;case "Building":sql="SELECT BuildingId Id,BuildingName Name FROM mst.Buildings WHERE IsActive=1 ORDER BY BuildingName";break;case "Floor":sql="SELECT FloorId Id,FloorName Name FROM mst.Floors WHERE IsActive=1 ORDER BY DisplayOrder";break;case "Room":sql="SELECT RoomId Id,RoomName Name FROM mst.Rooms WHERE IsActive=1 ORDER BY RoomName";break;default:throw new ArgumentOutOfRangeException(nameof(type));}using(var c=Db.OpenConnection())using(var cmd=new SqlCommand(sql,c)){var t=new DataTable();using(var a=new SqlDataAdapter(cmd))a.Fill(t);return t;}}
  public DataTable GetRegister(string query){const string sql=@"SELECT TOP(500) f.FixedAssetNo,f.AssetName,c.CategoryName,d.DepartmentName,u.DisplayName Custodian,b.BuildingName,fl.FloorName,r.RoomName,f.Quantity,m.UomCode,f.AssetStatus,f.AcquisitionCost FROM fa.FixedAssets f INNER JOIN mst.AssetCategories c ON c.CategoryId=f.CategoryId INNER JOIN mst.Departments d ON d.DepartmentId=f.DepartmentId LEFT JOIN sec.Users u ON u.UserId=f.CustodianUserId LEFT JOIN mst.Buildings b ON b.BuildingId=f.BuildingId LEFT JOIN mst.Floors fl ON fl.FloorId=f.FloorId LEFT JOIN mst.Rooms r ON r.RoomId=f.RoomId LEFT JOIN mst.Uoms m ON m.UomId=f.UomId WHERE (@Query='' OR f.FixedAssetNo LIKE '%'+@Query+'%' OR f.AssetName LIKE '%'+@Query+'%' OR f.SerialNumber LIKE '%'+@Query+'%') ORDER BY f.FixedAssetNo;";using(var c=Db.OpenConnection())using(var cmd=new SqlCommand(sql,c)){cmd.Parameters.Add(Db.Parameter("@Query",query??string.Empty,SqlDbType.NVarChar,150));var t=new DataTable();using(var a=new SqlDataAdapter(cmd))a.Fill(t);return t;}}
  public long SaveDraft(AssetSurvey s,SurveyAccessContext access){if(s.SurveyId>0&&!new AssetSurveyRepository().CanEdit(s.SurveyId,access))throw new InvalidOperationException("Only the owner can update a Draft or Returned survey.");s.SurveyorUserId=access.UserId;using(var c=Db.OpenConnection())using(var cmd=new SqlCommand("fa.usp_SaveAssetSurvey",c)){cmd.CommandType=CommandType.StoredProcedure;Add(cmd,"@SurveyId",s.SurveyId,SqlDbType.BigInt);Add(cmd,"@SurveyorUserId",s.SurveyorUserId,SqlDbType.Int);Add(cmd,"@SurveyDate",s.SurveyDate,SqlDbType.Date);Add(cmd,"@DepartmentId",s.DepartmentId,SqlDbType.Int);Add(cmd,"@CustodianUserId",s.CustodianUserId==0?(object)null:s.CustodianUserId,SqlDbType.Int);Add(cmd,"@AssetName",s.AssetName,SqlDbType.NVarChar,250);Add(cmd,"@CategoryId",s.CategoryId,SqlDbType.Int);Add(cmd,"@Brand",s.Brand,SqlDbType.NVarChar,120);Add(cmd,"@ModelDescription",s.ModelDescription,SqlDbType.NVarChar,300);Add(cmd,"@SerialNumber",s.SerialNumber,SqlDbType.NVarChar,150);Add(cmd,"@OwnershipType",s.OwnershipType,SqlDbType.NVarChar,50);Add(cmd,"@ConditionId",s.ConditionId,SqlDbType.Int);Add(cmd,"@WidthCm",s.WidthCm,SqlDbType.Decimal);Add(cmd,"@LengthCm",s.LengthCm,SqlDbType.Decimal);Add(cmd,"@HeightCm",s.HeightCm,SqlDbType.Decimal);Add(cmd,"@WeightKg",s.WeightKg,SqlDbType.Decimal);Add(cmd,"@Quantity",s.Quantity,SqlDbType.Decimal);Add(cmd,"@UomId",s.UomId,SqlDbType.Int);Add(cmd,"@BuildingId",s.BuildingId,SqlDbType.Int);Add(cmd,"@FloorId",s.FloorId,SqlDbType.Int);Add(cmd,"@RoomId",s.RoomId,SqlDbType.Int);Add(cmd,"@ReceivedDate",s.ReceivedDate,SqlDbType.Date);Add(cmd,"@PurchaseOrderNo",s.PurchaseOrderNo,SqlDbType.NVarChar,100);Add(cmd,"@EstimatedValue",s.EstimatedValue,SqlDbType.Decimal);Add(cmd,"@MissingDimensionReason",s.MissingDimensionReason,SqlDbType.NVarChar,500);Add(cmd,"@Remark",s.Remark,SqlDbType.NVarChar,1000);var output=new SqlParameter("@SavedSurveyId",SqlDbType.BigInt){Direction=ParameterDirection.Output};cmd.Parameters.Add(output);cmd.ExecuteNonQuery();return Convert.ToInt64(output.Value);}}
  private static void Add(SqlCommand cmd,string name,object value,SqlDbType type,int size=0){var p=Db.Parameter(name,value,type,size);if(type==SqlDbType.Decimal){p.Precision=18;p.Scale=2;}cmd.Parameters.Add(p);}
 }
}
