<%@ Page Title="Asset Register" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="List.aspx.cs" Inherits="BC.FixedAsset.Web.FixedAsset.Register.AssetRegister" %>
<asp:Content ID="Body" ContentPlaceHolderID="MainContent" runat="server">
<div class="page-head"><div><h1>Asset Register</h1><p>ทะเบียนทรัพย์สินกลางและสถานะปัจจุบัน</p></div></div><asp:Label ID="lblMessage" runat="server" CssClass="message"/>
<section class="card table-card"><div class="table-toolbar"><div class="search-box"><asp:TextBox ID="txtSearch" runat="server" placeholder="ค้นหา Asset ID, ชื่อ หรือ Serial"/><asp:Button ID="btnSearch" runat="server" CssClass="button outline compact" Text="ค้นหา" OnClick="Search_Click"/></div></div><div class="table-wrap"><asp:GridView ID="gridAssets" runat="server" AutoGenerateColumns="false" GridLines="None" OnRowCommand="Grid_RowCommand" OnRowDataBound="Grid_RowDataBound" CssClass="asset-table"><Columns>
<asp:TemplateField HeaderText="Fixed Asset ID"><ItemTemplate><%# Eval("FixedAssetNo") %><asp:LinkButton ID="btnDetail" runat="server" CssClass="row-detail-trigger" CommandName="Detail" CommandArgument='<%# Eval("FixedAssetId") %>' Text="ดูรายละเอียด"/></ItemTemplate></asp:TemplateField>
<asp:BoundField DataField="AssetName" HeaderText="Asset"/><asp:BoundField DataField="CategoryName" HeaderText="Category"/><asp:BoundField DataField="DepartmentName" HeaderText="Department"/><asp:BoundField DataField="Custodian" HeaderText="Custodian"/><asp:BoundField DataField="Quantity" HeaderText="Qty"/><asp:BoundField DataField="UomCode" HeaderText="UOM"/><asp:BoundField DataField="AssetStatus" HeaderText="Status"/>
<asp:TemplateField HeaderText="ดำเนินการ"><ItemTemplate><asp:HyperLink runat="server" CssClass="button small outline" NavigateUrl='<%# "../Tag.aspx?assetId="+Eval("FixedAssetId") %>' Target="_blank">Print Tag</asp:HyperLink></ItemTemplate></asp:TemplateField>
</Columns></asp:GridView></div></section>
<asp:Panel ID="pnlDetail" runat="server" CssClass="modal-layer" Visible="false"><div class="modal-card"><div class="modal-head"><div><h2>Asset Register Detail</h2><p class="muted">รายละเอียดทรัพย์สินและสถานะทะเบียน</p></div><asp:Button ID="btnClose" runat="server" Text="×" CssClass="icon-button" OnClick="Close_Click" CausesValidation="false"/></div><div class="detail-images"><asp:Repeater ID="repImages" runat="server"><ItemTemplate><figure><img src='<%# AttachmentUrl(Eval("AttachmentId")) %>' alt='<%# Eval("AttachmentType") %>'/><figcaption><%# Eval("AttachmentType") %></figcaption></figure></ItemTemplate></asp:Repeater></div><asp:Literal ID="litDetail" runat="server"/></div></asp:Panel>
</asp:Content>
